In [40]:
import io,os,sys,types,time,math,DateTime,random,requests,subprocess,tempfile
from io import StringIO

In [ ]:
#!conda install --yes -c conda-forge missingno

In [ ]:
!conda install --yes -c anaconda requests

In [ ]:
!conda update --yes --all

In [1]:
import numpy as np
import pandas as pd

In [1]:
# visualization
import matplotlib.pyplot as plt
#import missingno
import seaborn as sns
from pandas.tools.plotting import scatter_matrix
from mpl_toolkits.mplot3d import Axes3D


In [10]:
# Feature Selection and Encoding
from sklearn.feature_selection import RFE,RFECV
from sklearn.svm import SVR
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,label_binarize

In [7]:
# Machine learning
import sklearn.ensemble as ske
from sklearn import datasets,model_selection,tree,preprocessing,metrics,linear_model
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso,SGDClassifier
from sklearn.tree import DecisionTreeClassifier
#import tensorflow as tf

In [9]:
# Grid and Random Search
import scipy.stats as st
from scipy.stats import randint as sp_randint
from sklearn.model_selection import GridSearchCV


In [10]:
# Metrics
from sklearn.metrics import precision_recall_fscore_support,roc_curve,auc

In [11]:
# Managing Warnings
import warnings
warnings.filterwarnings('ignore')
#plot the Figures Inline
%matplotlib inline

In [1]:
# Download 
DATASET = (
     "http://archive.ics.uci.edu/ml/machine-learning-database/adult/adult.data",
     "http://archive.ics.uci.edu/ml/machine-learning-database/adult/adult.names",
     "http://archive.ics.uci.edu/ml/machine-learning-database/adult/adult.test",
)

In [12]:
# Load Training and test data sets
import pandas as pd
headers = ['age','workclass','fnlwgt',
           'education','eduction_num',
           'marital-status','occupation',
           'relationship','race','sex',
           'capital-gain','capital-loss',
           'hours-per-week','native-country',
           'predclass']
training_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                          header=None,
                          names= headers,na_values=["?"])
test_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                      header=None,
                      names=headers,na_values=["?"])
dataset_raw = training_raw.append(test_raw)
dataset_raw.reset_index(inplace=True)
dataset_raw.drop("index",inplace=True,axis=1)

In [14]:
dataset_raw = training_raw.append(test_raw)
dataset_raw.reset_index(inplace=True)
dataset_raw.drop("index",inplace=True,axis=1)

In [14]:
dataset_raw

age          workclass  fnlwgt      education  eduction_num  \
0       39          State-gov   77516      Bachelors            13   
1       50   Self-emp-not-inc   83311      Bachelors            13   
2       38            Private  215646        HS-grad             9   
3       53            Private  234721           11th             7   
4       28            Private  338409      Bachelors            13   
5       37            Private  284582        Masters            14   
6       49            Private  160187            9th             5   
7       52   Self-emp-not-inc  209642        HS-grad             9   
8       31            Private   45781        Masters            14   
9       42            Private  159449      Bachelors            13   
10      37            Private  280464   Some-college            10   
11      30          State-gov  141297      Bachelors            13   
12      23            Private  122272      Bachelors            13   
13      32            Private  205019     Assoc-acdm            12   
14      40            Private  121772      Assoc-voc            11   
15      34            Private  245487        7th-8th             4   
16      25   Self-emp-not-inc  176756        HS-grad             9   
17      32            Private  186824        HS-grad             9   
18      38            Private   28887           11th             7   
19      43   Self-emp-not-inc  292175        Masters            14   
20      40            Private  193524      Doctorate            16   
21      54            Private  302146        HS-grad             9   
22      35        Federal-gov   76845            9th             5   
23      43            Private  117037           11th             7   
24      59            Private  109015        HS-grad             9   
25      56          Local-gov  216851      Bachelors            13   
26      19            Private  168294        HS-grad             9   
27      54                  ?  180211   Some-college            10   
28      39            Private  367260        HS-grad             9   
29      49            Private  193366        HS-grad             9   
...    ...                ...     ...            ...           ...   
32531   30                  ?   33811      Bachelors            13   
32532   34            Private  204461      Doctorate            16   
32533   54            Private  337992      Bachelors            13   
32534   37            Private  179137   Some-college            10   
32535   22            Private  325033           12th             8   
32536   34            Private  160216      Bachelors            13   
32537   30            Private  345898        HS-grad             9   
32538   38            Private  139180      Bachelors            13   
32539   71                  ?  287372      Doctorate            16   
32540   45          State-gov  252208        HS-grad             9   
32541   41                  ?  202822        HS-grad             9   
32542   72                  ?  129912        HS-grad             9   
32543   45          Local-gov  119199     Assoc-acdm            12   
32544   31            Private  199655        Masters            14   
32545   39          Local-gov  111499     Assoc-acdm            12   
32546   37            Private  198216     Assoc-acdm            12   
32547   43            Private  260761        HS-grad             9   
32548   65   Self-emp-not-inc   99359    Prof-school            15   
32549   43          State-gov  255835   Some-college            10   
32550   43   Self-emp-not-inc   27242   Some-college            10   
32551   32            Private   34066           10th             6   
32552   43            Private   84661      Assoc-voc            11   
32553   32            Private  116138        Masters            14   
32554   53            Private  321865        Masters            14   
32555   22            Private  310152   Some-college            10   
32556   27       

In [9]:
dataset_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48843 entries, 0 to 48842
Data columns (total 15 columns):
age               48843 non-null object
workclass         48842 non-null object
fnlwgt            48842 non-null float64
education         48842 non-null object
eduction_num      48842 non-null float64
marital-status    48842 non-null object
occupation        48842 non-null object
relationship      48842 non-null object
race              48842 non-null object
sex               48842 non-null object
capital-gain      48842 non-null float64
capital-loss      48842 non-null float64
hours-per-week    48842 non-null float64
native-country    48842 non-null object
predclass         48842 non-null object
dtypes: float64(5), object(10)
memory usage: 3.7+ MB


In [16]:
dataset_raw.describe()

fnlwgt  eduction_num  capital-gain  capital-loss  hours-per-week
count  4.884200e+04  48842.000000  48842.000000  48842.000000    48842.000000
mean   1.896641e+05     10.078089   1079.067626     87.502314       40.422382
std    1.056040e+05      2.570973   7452.019058    403.004552       12.391444
min    1.228500e+04      1.000000      0.000000      0.000000        1.000000
25%    1.175505e+05      9.000000      0.000000      0.000000       40.000000
50%    1.781445e+05     10.000000      0.000000      0.000000       40.000000
75%    2.376420e+05     12.000000      0.000000      0.000000       45.000000
max    1.490400e+06     16.000000  99999.000000   4356.000000       99.000000

In [17]:
dataset_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
eduction_num      32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
predclass         32561 non-null object
dtypes: int64(6), object(9)
memory usage: 2.6+ MB


In [41]:
import pandas as pd
headers = ['age','workclass','fnlwgt',
           'education','eduction_num',
           'marital-status','occupation',
           'relationship','race','sex',
           'capital-gain','capital-loss',
           'hours-per-week','native-country',
           'predclass']
training_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                          header=None,
                          names= headers,na_values=["?"])
test_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                      header=None,
                      names=headers,na_values=["?"])
dataset_raw = training_raw.append(test_raw)
dataset_raw
dataset_raw1 = dataset_raw.drop(columns = 'predclass')
dataset_raw1 = dataset_raw.drop(columns = "native-country")

#dataset_raw = dataset_raw.reset_index(inplace=True)

#dataset_raw.drop("age",inplace=True,axis=1)
#dataset_raw1= dataset_raw.drop()
#dataset_raw1 = dataset_raw1.dropna("predclass",axis=1,inplace=True)
dataset_raw1

age          workclass    fnlwgt      education  eduction_num  \
0      39          State-gov   77516.0      Bachelors          13.0   
1      50   Self-emp-not-inc   83311.0      Bachelors          13.0   
2      38            Private  215646.0        HS-grad           9.0   
3      53            Private  234721.0           11th           7.0   
4      28            Private  338409.0      Bachelors          13.0   
5      37            Private  284582.0        Masters          14.0   
6      49            Private  160187.0            9th           5.0   
7      52   Self-emp-not-inc  209642.0        HS-grad           9.0   
8      31            Private   45781.0        Masters          14.0   
9      42            Private  159449.0      Bachelors          13.0   
10     37            Private  280464.0   Some-college          10.0   
11     30          State-gov  141297.0      Bachelors          13.0   
12     23            Private  122272.0      Bachelors          13.0   
13     32            Private  205019.0     Assoc-acdm          12.0   
14     40            Private  121772.0      Assoc-voc          11.0   
15     34            Private  245487.0        7th-8th           4.0   
16     25   Self-emp-not-inc  176756.0        HS-grad           9.0   
17     32            Private  186824.0        HS-grad           9.0   
18     38            Private   28887.0           11th           7.0   
19     43   Self-emp-not-inc  292175.0        Masters          14.0   
20     40            Private  193524.0      Doctorate          16.0   
21     54            Private  302146.0        HS-grad           9.0   
22     35        Federal-gov   76845.0            9th           5.0   
23     43            Private  117037.0           11th           7.0   
24     59            Private  109015.0        HS-grad           9.0   
25     56          Local-gov  216851.0      Bachelors          13.0   
26     19            Private  168294.0        HS-grad           9.0   
27     54                  ?  180211.0   Some-college          10.0   
28     39            Private  367260.0        HS-grad           9.0   
29     49            Private  193366.0        HS-grad           9.0   
...    ..                ...       ...            ...           ...   
16252  81                  ?   26711.0      Assoc-voc          11.0   
16253  60            Private  117909.0      Assoc-voc          11.0   
16254  39            Private  229647.0      Bachelors          13.0   
16255  38            Private  149347.0        Masters          14.0   
16256  43          Local-gov   23157.0        Masters          14.0   
16257  23            Private   93977.0        HS-grad           9.0   
16258  73       Self-emp-inc  159691.0   Some-college          10.0   
16259  35            Private  176967.0   Some-college          10.0   
16260  66            Private  344436.0        HS-grad           9.0   
16261  27            Private  430340.0   Some-college          10.0   
16262  40            Private  202168.0    Prof-school          15.0   
16263  51            Private   82720.0        HS-grad           9.0   
16264  22            Private  269623.0   Some-college          10.0   
16265  64   Self-emp-not-inc  136405.0        HS-grad           9.0   
16266  50          Local-gov  139347.0        Masters          14.0   
16267  55            Private  224655.0        HS-grad           9.0   
16268  38            Private  247547.0      Assoc-voc          11.0   
16269  58            Private  292710.0     Assoc-acdm          12.0   
16270  32            Private  173449.0        HS-grad           9.0   
16271  48            Private  285570.0        HS-grad           9.0   
16272  61            Private   89686.0        HS-grad           9.0   
16273  31            Private  440129.0        HS-grad           9.0   
16274  25            Private  350977.0        HS-grad           9.0   
16275  48          Local-gov  349230.0        Masters          14.0   
16276  33            Private  

In [6]:
import numpy as np
import pandas as pd
headers = ['age','workclass','fnlwgt',
           'education','eduction_num',
           'marital-status','occupation',
           'relationship','race','sex',
           'capital-gain','capital-loss',
           'hours-per-week','native-country',
           'predclass']
training_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                          header=None,
                          names= headers,na_values=["?"])
test_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                      header=None,
                      names=headers,na_values=["?"])
dataset_raw = training_raw.append(test_raw)
dataset_raw
#dataset_raw1 = dataset_raw.drop(columns = 'predclass')

#dataset_raw['over50K'] = np.where(dataset_raw.predclass == '<=50K', 0, 1)
#dataset_raw['over50K']

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
16252    1
16253    1
16254    1
16255    1
16256    1
16257    1
16258    1
16259    1
16260    1
16261    1
16262    1
16263    1
16264    1
16265    1
16266    1
16267    1
16268    1
16269    1
16270    1
16271    1
16272    1
16273    1
16274    1
16275    1
16276    1
16277    1
16278    1
16279    1
16280    1
16281    1
Name: over50K, Length: 48843, dtype: int32

In [19]:
import pandas as pd
headers = ['age','workclass','fnlwgt',
           'education','eduction_num',
           'marital-status','occupation',
           'relationship','race','sex',
           'capital-gain','capital-loss',
           'hours-per-week','native-country',
           'predclass']
training_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                          header=None,
                          names= headers,na_values=["?"])
test_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                      header=None,
                      names=headers,na_values=["?"])
dataset_raw = training_raw
dataset_raw.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
eduction_num      0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
predclass         0
dtype: int64

In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
dataset_raw = ['age','workclass','fnlwgt','education','eduction_num', 'marital-status','occupation','relationship','race','sex', 'capital-gain','capital-loss','hours-per-week','native-country',]
values = array(dataset_raw) 
print(values)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['age' 'workclass' 'fnlwgt' 'education' 'eduction_num' 'marital-status'
 'occupation' 'relationship' 'race' 'sex' 'capital-gain' 'capital-loss'
 'hours-per-week' 'native-country']
[ 0 13  5  3  4  7  9 11 10 12  1  2  6  8]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.

In [7]:

dataset_raw2 = pd.get_dummies(dataset_raw)
dataset_raw2.head()

age  fnlwgt  eduction_num  capital-gain  capital-loss  hours-per-week  \
0   39   77516            13          2174             0              40   
1   50   83311            13             0             0              13   
2   38  215646             9             0             0              40   
3   53  234721             7             0             0              40   
4   28  338409            13             0             0              40   

   workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   

   workclass_ Never-worked       ...         native-country_ Scotland  \
0                        0       ...                                0   
1                        0       ...                                0   
2                        0       ...                                0   
3                        0       ...                                0   
4                        0       ...                                0   

   native-country_ South  native-country_ Taiwan  native-country_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   native-country_ Trinadad&Tobago  native-country_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   native-country_ Vietnam  native-country_ Yugoslavia  predclass_ <=50K  \
0                        0                           0                 1   
1                        0                           0                 1   
2                        0                           0                 1   
3                        0                           0                 1   
4                        0                           0                 1   

   predclass_ >50K  
0                0  
1                0  
2                0  
3                0  
4                0  

[5 rows x 110 columns]

In [8]:
dataset_raw2 = pd.get_dummies(dataset_raw)
dataset_raw2.isnull().sum()

age                                           0
fnlwgt                                        0
eduction_num                                  0
capital-gain                                  0
capital-loss                                  0
hours-per-week                                0
workclass_ ?                                  0
workclass_ Federal-gov                        0
workclass_ Local-gov                          0
workclass_ Never-worked                       0
workclass_ Private                            0
workclass_ Self-emp-inc                       0
workclass_ Self-emp-not-inc                   0
workclass_ State-gov                          0
workclass_ Without-pay                        0
education_ 10th                               0
education_ 11th                               0
education_ 12th                               0
education_ 1st-4th                            0
education_ 5th-6th                            0
education_ 7th-8th                      

In [31]:
y = dataset_raw['over50K']
X =dataset_raw2

In [25]:
# Import train_test_split
from sklearn.cross_validation import train_test_split

# Split the 'features' and 'income' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ( "Testing set has {} samples.".format(X_test.shape[0]))

C:\Users\sowmy\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Training set has 39074 samples.
Testing set has 9769 samples.


In [16]:
dataset_raw2 = dataset_raw2.fillna(lambda x : x.median())
dataset_raw2

age  fnlwgt  eduction_num  capital-gain  capital-loss  hours-per-week  \
0       39   77516            13          2174             0              40   
1       50   83311            13             0             0              13   
2       38  215646             9             0             0              40   
3       53  234721             7             0             0              40   
4       28  338409            13             0             0              40   
5       37  284582            14             0             0              40   
6       49  160187             5             0             0              16   
7       52  209642             9             0             0              45   
8       31   45781            14         14084             0              50   
9       42  159449            13          5178             0              40   
10      37  280464            10             0             0              80   
11      30  141297            13             0             0              40   
12      23  122272            13             0             0              30   
13      32  205019            12             0             0              50   
14      40  121772            11             0             0              40   
15      34  245487             4             0             0              45   
16      25  176756             9             0             0              35   
17      32  186824             9             0             0              40   
18      38   28887             7             0             0              50   
19      43  292175            14             0             0              45   
20      40  193524            16             0             0              60   
21      54  302146             9             0             0              20   
22      35   76845             5             0             0              40   
23      43  117037             7             0          2042              40   
24      59  109015             9             0             0              40   
25      56  216851            13             0             0              40   
26      19  168294             9             0             0              40   
27      54  180211            10             0             0              60   
28      39  367260             9             0             0              80   
29      49  193366             9             0             0              40   
...    ...     ...           ...           ...           ...             ...   
32531   30   33811            13             0             0              99   
32532   34  204461            16             0             0              60   
32533   54  337992            13             0             0              50   
32534   37  179137            10             0             0              39   
32535   22  325033             8             0             0              35   
32536   34  160216            13             0             0              55   
32537   30  345898             9             0             0              46   
32538   38  139180            13         15020             0              45   
32539   71  287372            16             0             0              10   
32540   45  252208             9             0             0              40   
32541   41  202822             9             0             0              32   
32542   72  129912             9             0             0              25   
32543   45  119199            12             0             0              48   
32544   31  199655            14             0             0              30   
32545   39  111499            12             0             0              20   
32546   37  198216            12             0             0              40   
32547   43  260761             9             0             0              40   
32548   65   99359            15          1086             0              60   
32549  

In [8]:
import sklearn.ensemble as ske
import numpy as np
from sklearn import datasets,model_selection,tree,preprocessing,metrics,linear_model
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso,SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold, learning_curve, train_test_split, KFold

import pandas as pd
headers = ['age','workclass','fnlwgt',
           'education','eduction_num',
           'marital-status','occupation',
           'relationship','race','sex',
           'capital-gain','capital-loss',
           'hours-per-week','native-country',
           'predclass']
training_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                          header=None,
                          names= headers,na_values=["?"])
test_raw = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                      header=None,
                      names=headers,na_values=["?"])
dataset_raw = training_raw.append(test_raw)

validation_size = 0.20
seed = 7
num_folds = 10
scoring = 'accuracy'
dataset_raw['over50K'] = np.where(dataset_raw.predclass == '<=50K', 0, 1)

dataset_raw2 = pd.get_dummies(dataset_raw)
print(dataset_raw2)


y = dataset_raw['over50K']
X =dataset_raw2
X_train, X_validation, Y_train, Y_validation = train_test_split(X,y,
    test_size=validation_size,random_state=seed)

# Params for Random Forest
num_trees = 10
max_features = 3

#Spot Check 5 Algorithms (LR, LDA, KNN, CART, GNB, SVM)
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('RF', RandomForestClassifier(n_estimators=num_trees, max_features=max_features)))
#models.append(('SVM', SVC()))
# evalutate each model in turn
results = []
names = []
for name, model in models:
    kfold = KFold(n_splits=10, random_state=seed)
    #cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
    cv_results = cross_val_score(model, X_train, Y_train, cv=kfold)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)


         fnlwgt  eduction_num  capital-gain  capital-loss  hours-per-week  \
0       77516.0          13.0        2174.0           0.0            40.0   
1       83311.0          13.0           0.0           0.0            13.0   
2      215646.0           9.0           0.0           0.0            40.0   
3      234721.0           7.0           0.0           0.0            40.0   
4      338409.0          13.0           0.0           0.0            40.0   
5      284582.0          14.0           0.0           0.0            40.0   
6      160187.0           5.0           0.0           0.0            16.0   
7      209642.0           9.0           0.0           0.0            45.0   
8       45781.0          14.0       14084.0           0.0            50.0   
9      159449.0          13.0        5178.0           0.0            40.0   
10     280464.0          10.0           0.0           0.0            80.0   
11     141297.0          13.0           0.0           0.0            40.0   

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').